# 文件路径: .github/workflows/update_tags.yml

name: Update All Stock Data & Tags Daily

on:
  schedule:
    # 每天 UTC 时间 8点 (北京时间下午4点) - 一个更适合美股收盘后的时间
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-all-data-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API to trigger a unified data update
        env:
          # ** 确保 GitHub Secrets 的名字是 VERCEL_URL **
          DEPLOYMENT_URL: ${{ secrets.VERCEL_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          # ** 只调用一个、全功能的 API 端点 **
          curl --fail --max-time 300 -X GET \
            -H "Authorization: Bearer $CRON_SECRET" \
            "$DEPLOYMENT_URL/api/update-all-data"